name: flutter_food_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <5.0.0'
  flutter: 3.27.3

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  http: ^0.13.6
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
